config/routes.rb
Rails.application.routes.draw do
  
  resources :accesory_sales
  namespace :api do
    resources :clients
  end
  resources :lent_accesories do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :lent_kinds do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :info_sales do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :sales do 
    match 'search', :via => [:post,:get], :on => :collection
    match 'search_client',:via =>[:get], :on => :collection   
  end  

  resources :lent_types do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :history_clients do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :monture_types do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :lent_models do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :lent_marks do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :lent_colors do
    match 'search', :via => [:post,:get], :on => :collection
  end
  
  resources :lent_serials do
    match 'search', :via => [:post,:get], :on => :collection
    match 'find_type_model',:via =>[:get], :on => :collection      
  end

  resources :suppliers do
    match 'search', :via => [:post,:get], :on => :collection
    match 'find_type_doc',:via =>[:get], :on => :collection  
  end

  resources :clients do
    match 'search', :via => [:post,:get], :on => :collection
    match 'find_type_doc',:via =>[:get], :on => :collection      
    resources :history_clients    
  end
 

  resources :type_clients do
     match 'search', :via => [:post,:get], :on => :collection
  end

  resources :type_docs do
     match 'search', :via => [:post,:get], :on => :collection
  end

  resources :accounts do
     match 'search', :via => [:post,:get], :on => :collection
  end
  
  resources :dashboards

  devise_for :users,controllers: {sessions: 'sessions'}
  
  resources :users

   root 'home#index'  
end

app/models/lent_accesory.rb
class LentAccesory < ApplicationRecord
  has_many :accesory_sales
##################################################

  def str_name_sale
    "#{name} (P.min: #{price_cost} / P.Max: #{price_shop}" 
  end
##################################################
  
  #PAGINACION = 10
  self.per_page = 10

##################################################

end

app/controllers/lent_accesories_controller.rb
class LentAccesoriesController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_lent_accesory, only: [:show, :edit, :update, :destroy]
################################################

  def search
    index
    render :index
  end
  # GET /lent_accesories
  # GET /lent_accesories.json
  def index
    @search_name = params[:search_name]

    # INICIO RANSACK
    @query = LentAccesory.ransack(params[:q])    
    @query.name_cont = @search_name if @search_name.present?

    # PAGINACION Y ORDEN
    @results =  @query.result(distinct: true).paginate(:page => params[:page] )
     
    # RESULTADO FINAL
    @lent_accesories = @results   
  end

  # GET /lent_accesories/1
  # GET /lent_accesories/1.json
  def show
  end

  # GET /lent_accesories/new
  def new
    @lent_accesory = LentAccesory.new
  end

  # GET /lent_accesories/1/edit
  def edit
  end

  # POST /lent_accesories
  # POST /lent_accesories.json
  def create
    @lent_accesory = LentAccesory.new(lent_accesory_params)

    respond_to do |format|
      if @lent_accesory.save
        format.html { 
          redirect_to @lent_accesory
          flash[:success] = 'Se ha creado.' }
        format.json { render :show, status: :created, location: @lent_accesory }
      else
        format.html { render :new }
        format.json { render json: @lent_accesory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lent_accesories/1
  # PATCH/PUT /lent_accesories/1.json
  def update
    respond_to do |format|
      if @lent_accesory.update(lent_accesory_params)
        format.html { 
          redirect_to @lent_accesory
          flash[:success] = 'Se ha actualizado.' }
        format.json { render :show, status: :ok, location: @lent_accesory }
      else
        format.html { render :edit }
        format.json { render json: @lent_accesory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lent_accesories/1
  # DELETE /lent_accesories/1.json
  def destroy
    @lent_accesory.destroy
    respond_to do |format|
      format.html { 
        redirect_to lent_accesories_url
        flash[:danger] = 'Se ha eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lent_accesory
      @lent_accesory = LentAccesory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lent_accesory_params
      params.require(:lent_accesory).permit(:name, :price_cost, :price_shop)
    end
end

app/helpers/lent_accesories_helper.rb
module LentAccesoriesHelper
end

app/views/lent_accesories/_form.html.erb
<% javascript "jquery/jquery-1.8.2.min.js" %>
<% javascript "jquery/jquery.validationEngine","jquery/jquery.validationEngine-es" %>
<% jquery_validationengine "validate_form" %>
<% stylesheet "validationEngine.jquery" %>

<%= form_for(lent_accesory,:html => {id: "validate_form"})do |f| %>
  <% if lent_accesory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lent_accesory.errors.count, "error") %> prohibited this lent_accesory from being saved:</h2>

      <ul>
      <% lent_accesory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
 

<div class="row">
  <div class="col-xs-3"><strong>Nombre:</strong></div>
  <div class="col-xs-6"><%= f.text_field :name ,class:"form-control validate[required]" %></div>
</div>

<br>
<div class="row">
  <div class="col-xs-3"><strong>Precio de Costo:</strong></div>
  <div class="col-xs-6"><%= f.text_field :price_cost ,class:"form-control validate[required]" %></div>
</div>

<br>
<div class="row">
  <div class="col-xs-3"><strong>Precio de Lista:</strong></div>
  <div class="col-xs-6"><%= f.text_field :price_shop ,class:"form-control validate[required]" %></div>
</div>

<br>
<div class="actions" align="center">
  <%= f.submit "Guardar", class: "btn btn-success" %>
  <%= link_to 'Regresar', lent_accesories_path , class: "btn btn-warning"%>
</div>
<% end %>

app/views/lent_accesories/edit.html.erb
<h1 align="center">Editar Accesorio de Lente</h1>
<br>

<%= render 'form', lent_accesory: @lent_accesory %>
 

app/views/lent_accesories/index.html.erb
<h1 align="center">Accesorios de Lentes</h1>
<br>

<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Búsqueda</h4>
  </div>
  <div class="panel-body">
    <%= form_for @query, url: [:search,:lent_accesories], html: { method: 'post'}  do %> 
      <p><label>Accesorio:</label>
      <%= text_field_tag "search_name", params[:search_name], class: "form-control" %></p>
      <p><%= submit_tag "Buscar",:class=>"btn bg-color-blueDark txt-color-white" %></p> 
    <% end %>
  </div>
</div>

<br>
<%= link_to 'Nuevo Accesorio del Lente', new_lent_accesory_path, class: "btn btn-primary" %>
<br><br>

<div class="table-responsive">
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Nombre</th>
        <th>Precios Entre</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
    <% @lent_accesories.each do |lent_accesory| %>
      <tr>
        <td><%= lent_accesory.name %></td>
        <td><b>S/.<%= lent_accesory.price_cost %></b> a  <b>S/.<%= lent_accesory.price_shop %></b></td>
        <td>
        <%= link_to "<span class='glyphicon glyphicon-zoom-in' aria-hidden='true'></span>".html_safe, lent_accesory, class: "btn btn-info"  %>
        <%= link_to "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span>".html_safe, edit_lent_accesory_path(lent_accesory) ,class: "btn btn-success"  %>
        <%= link_to "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span>".html_safe, lent_accesory, class: "btn btn-danger", method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div  class="col-sm-6 text-main"><br/><br/>
  <%= page_entries_info  @lent_accesories  , :page_links => false %>
</div>

<div  class="col-sm-6 text-right">
  <%= will_paginate @lent_accesories, :params => params, :class => 'pagination2', :previous_label=>">", :next_label => ">",inner_window: 1, outer_window: 1 %>
</div>




 

app/views/lent_accesories/new.html.erb
<h1 align="center">Nuevo Accesorio de Lente</h1>
<br>

<%= render 'form', lent_accesory: @lent_accesory %>
 

app/views/lent_accesories/show.html.erb
 
<h1 align="center">Ver Accesorio de Lente</h1>
<br>

<div class="row">
  <div class="col-xs-3"><strong>Nombre:</strong></div>
  <div class="col-xs-6"><%= @lent_accesory.name %></div>
</div>

<br>
<div class="row">
  <div class="col-xs-3"><strong>Precio de Costo:</strong></div>
  <div class="col-xs-6"><%= @lent_accesory.price_cost %></div>
</div>

<br>
<div class="row">
  <div class="col-xs-3"><strong>Precio de Lista:</strong></div>
  <div class="col-xs-6"><%= @lent_accesory.price_shop %></div>
</div>


<br>
<div class="actions" align="center"> 
  <%= link_to 'Editar', edit_lent_accesory_path(@lent_accesory), class: "btn btn-success" %>  
  <%= link_to 'Regresar', lent_accesories_path , class: "btn btn-warning"%>
</div>

  