config/routes.rb
Rails.application.routes.draw do
  
  resources :accesory_sales
  namespace :api do
    resources :clients
  end
  resources :lent_accesories do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :lent_kinds do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :info_sales do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :sales do 
    match 'search', :via => [:post,:get], :on => :collection
    match 'search_client',:via =>[:get], :on => :collection   
  end  

  resources :lent_types do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :history_clients do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :monture_types do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :lent_models do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :lent_marks do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :lent_colors do
    match 'search', :via => [:post,:get], :on => :collection
  end
  
  resources :lent_serials do
    match 'search', :via => [:post,:get], :on => :collection
    match 'find_type_model',:via =>[:get], :on => :collection      
  end

  resources :suppliers do
    match 'search', :via => [:post,:get], :on => :collection
    match 'find_type_doc',:via =>[:get], :on => :collection  
  end

  resources :clients do
    match 'search', :via => [:post,:get], :on => :collection
    match 'find_type_doc',:via =>[:get], :on => :collection      
    resources :history_clients    
  end
 

  resources :type_clients do
     match 'search', :via => [:post,:get], :on => :collection
  end

  resources :type_docs do
     match 'search', :via => [:post,:get], :on => :collection
  end

  resources :accounts do
     match 'search', :via => [:post,:get], :on => :collection
  end
  
  resources :dashboards

  devise_for :users,controllers: {sessions: 'sessions'}
  
  resources :users

   root 'home#index'  
end

app/models/type_client.rb
class TypeClient < ApplicationRecord
	has_many :type_docs
	validates :name, uniqueness: { case_sensitive: true }
##################################################

  #PAGINACION = 10
  self.per_page = 10

##################################################

end

app/controllers/type_clients_controller.rb
class TypeClientsController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_type_client, only: [:show, :edit, :update, :destroy]
################################################

  def search
    index
    render :index
  end
  
  # GET /type_accounts
  # GET /type_accounts.json
  def index
    @search_name = params[:search_name]

    # INICIO RANSACK
    @query = TypeClient.ransack(params[:q])    
    @query.name_cont = @search_name if @search_name.present?

    # PAGINACION Y ORDEN
    @results =  @query.result(distinct: true).paginate(:page => params[:page] )
     
    # RESULTADO FINAL
    @type_clients = @results 
  end

  # GET /type_accounts/1
  # GET /type_accounts/1.json
  def show
  end

  # GET /type_accounts/new
  def new
    @type_client = TypeClient.new
  end

  # GET /type_accounts/1/edit
  def edit
  end

  # POST /type_accounts
  # POST /type_accounts.json
  def create
    @type_client = TypeClient.new(type_client_params)

    respond_to do |format|
      if @type_client.save
        format.html { 
          redirect_to @type_client
          flash[:success] = 'Se ha creado.' }
        format.json { render :show, status: :created, location: @type_client }
      else
        format.html { render :new }
        format.json { render json: @type_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /type_accounts/1
  # PATCH/PUT /type_accounts/1.json
  def update
    respond_to do |format|
      if @type_client.update(type_client_params)
        format.html { 
          redirect_to @type_client
          flash[:success] = 'Se ha actualizado.' }
        format.json { render :show, status: :ok, location: @type_client }
      else
        format.html { render :edit }
        format.json { render json: @type_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_accounts/1
  # DELETE /type_accounts/1.json
  def destroy
    @type_client.destroy
    respond_to do |format|
      format.html { 
        redirect_to type_clients_url
        flash[:danger] = 'Se ha eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_client
      @type_client = TypeClient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_client_params
      params.require(:type_client).permit(:name)
    end
end

app/helpers/type_clients_helper.rb
module TypeClientsHelper
end

app/views/type_clients/_form.html.erb
<% javascript "jquery/jquery-1.8.2.min.js" %>
<% javascript "jquery/jquery.validationEngine","jquery/jquery.validationEngine-es" %>
<% jquery_validationengine "validate_form" %>
<% stylesheet "validationEngine.jquery" %>

<%= form_for(type_client,:html => {id: "validate_form"}) do |f| %>
  <% if type_client.errors.any? %>
    <div id="error_explanation">
      <h2 class="container alert alert-danger"><%= pluralize(type_client.errors.count, "error") %> encontrado:</h2>

      <ul>
      <% type_client.errors.full_messages.each do |message| %>
        <li class="container alert alert-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-xs-3"><strong>Nombre:</strong></div>
  <div class="col-xs-6"><%= f.text_field :name ,class:"form-control validate[required]" %></div>
</div>

<br>
<div class="actions" align="center">
  <%= f.submit "Guardar", class: "btn btn-success" %>
  <%= link_to 'Regresar', type_clients_path , class: "btn btn-warning"%>
</div>
<% end %>

app/views/type_clients/edit.html.erb
<h1 align="center">Editar Tipo de Cliente</h1>
<br>

<%= render 'form', type_client: @type_client %>
 

app/views/type_clients/index.html.erb
<h1 align="center">Tipos de Cliente</h1>
<br>

<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Búsqueda</h4>
  </div>
  <div class="panel-body">
    <%= form_for @query, url: [:search,:type_clients], html: { method: 'post'}  do %> 
      <p><label>Tipo de Cliente:</label>
      <%= text_field_tag "search_name", params[:search_name], class: "form-control" %></p>
      <p><%= submit_tag "Buscar",:class=>"btn bg-color-blueDark txt-color-white" %></p> 
    <% end %>
  </div>
</div>

<br>
<%= link_to 'Nuevo Tipo de Cliente', new_type_client_path, class: "btn btn-primary" %>
<br><br>

<div class="table-responsive">
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Nombre</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
    <% @type_clients.each do |type_client| %>
      <tr>
        <td><%= type_client.name %></td>
        <td>
        <%= link_to "<span class='glyphicon glyphicon-zoom-in' aria-hidden='true'></span>".html_safe, type_client, class: "btn btn-info"  %>
        <%= link_to "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span>".html_safe, edit_type_client_path(type_client) ,class: "btn btn-success"  %>
        <%= link_to "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span>".html_safe, type_client, class: "btn btn-danger", method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div  class="col-sm-6 text-main"><br/><br/>
  <%= page_entries_info  @type_clients  , :page_links => false %>
</div>

<div  class="col-sm-6 text-right">
  <%= will_paginate @type_clients, :params => params, :class => 'pagination2', :previous_label=>">", :next_label => ">",inner_window: 1, outer_window: 1 %>
</div>

app/views/type_clients/new.html.erb
<h1 align="center">Nuevo Tipo de Cliente</h1>
<br>

<%= render 'form', type_client: @type_client %>

app/views/type_clients/show.html.erb
 
<h1 align="center">Ver Tipo de Cliente</h1>
<br>

<div class="row">
  <div class="col-xs-3"><strong>Nombre:</strong></div>
  <div class="col-xs-6"><%= @type_client.name %></div>
</div>

<br>
<div class="actions" align="center"> 
  <%= link_to 'Editar', edit_type_client_path(@type_client), class: "btn btn-success" %>  
  <%= link_to 'Regresar', type_clients_path , class: "btn btn-warning"%>
</div>