config/routes.rb
Rails.application.routes.draw do
  
  resources :accesory_sales
  namespace :api do
    resources :clients
  end
  resources :lent_accesories do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :lent_kinds do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :info_sales do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :sales do 
    match 'search', :via => [:post,:get], :on => :collection
    match 'search_client',:via =>[:get], :on => :collection   
  end  

  resources :lent_types do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :history_clients do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :monture_types do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :lent_models do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :lent_marks do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :lent_colors do
    match 'search', :via => [:post,:get], :on => :collection
  end
  
  resources :lent_serials do
    match 'search', :via => [:post,:get], :on => :collection
    match 'find_type_model',:via =>[:get], :on => :collection      
  end

  resources :suppliers do
    match 'search', :via => [:post,:get], :on => :collection
    match 'find_type_doc',:via =>[:get], :on => :collection  
  end

  resources :clients do
    match 'search', :via => [:post,:get], :on => :collection
    match 'find_type_doc',:via =>[:get], :on => :collection      
    resources :history_clients    
  end
 

  resources :type_clients do
     match 'search', :via => [:post,:get], :on => :collection
  end

  resources :type_docs do
     match 'search', :via => [:post,:get], :on => :collection
  end

  resources :accounts do
     match 'search', :via => [:post,:get], :on => :collection
  end
  
  resources :dashboards

  devise_for :users,controllers: {sessions: 'sessions'}
  
  resources :users

   root 'home#index'  
end

app/models/accesory_sale.rb
class AccesorySale < ApplicationRecord
	belongs_to :lent_accesory
	belongs_to :sale
end

app/models/account.rb
class Account < ApplicationRecord
	##################################################

  #PAGINACION = 10
  self.per_page = 10

##################################################

end

app/models/client.rb
class Client < ApplicationRecord

  belongs_to :type_doc
  
  has_many :history_clients
  has_many :sales

  validates :num_doc, uniqueness: true

########################################

  def str_complete_name
   
      return self.try(:name).to_s + " " + self.try(:last_name).to_s + " " + self.try(:second_surname).to_s
     
   
  end
########################################

  def str_sex
    if self.sex.to_i == 1
      return "Masculino"
    else
      return "Femenino" 	
    end
  end
##################################################

  #PAGINACION = 10
  self.per_page = 10

##################################################
end

app/models/history_client.rb
class HistoryClient < ApplicationRecord
	belongs_to :client


  def str_past_lent_type
    @lent_type = LentType.where('id = ?', self.past_lent_type_id ).first
    return @lent_type.name
  end

  def str_current_lent_type
    @lent_type = LentType.where('id = ?', self.current_lent_type_id ).first
    return @lent_type.name
  end

  
############################################
 
  def str_consult_date
    return date_consult.strftime("%d/%m/%Y %I:%M %p")
  end
##################################################

  #PAGINACION = 10
  self.per_page = 10

##################################################


end

app/models/info_sale.rb
class InfoSale < ApplicationRecord
	belongs_to :sale
	belongs_to :lent_serial

##################################################

  #PAGINACION = 10
  self.per_page = 10

##################################################

end

app/models/lent_accesory.rb
class LentAccesory < ApplicationRecord
  has_many :accesory_sales
##################################################

  def str_name_sale
    "#{name} (P.min: #{price_cost} / P.Max: #{price_shop}" 
  end
##################################################
  
  #PAGINACION = 10
  self.per_page = 10

##################################################

end

app/models/lent_color.rb
class LentColor < ApplicationRecord
	has_many :lent_serials
	validates :name, uniqueness: { case_sensitive: true }
##################################################

  #PAGINACION = 10
  self.per_page = 10

##################################################
	
end

app/models/lent_kind.rb
class LentKind < ApplicationRecord
	has_many :lent_serials
##################################################

  #PAGINACION = 10
  self.per_page = 10

##################################################
	
end

app/models/lent_mark.rb
class LentMark < ApplicationRecord
	has_many :lent_models
	validates :name, uniqueness: { case_sensitive: true }
##################################################

  #PAGINACION = 10
  self.per_page = 10

##################################################
	
end

app/models/lent_model.rb
class LentModel < ApplicationRecord
	belongs_to :lent_mark

	has_many :lent_serials
	validates :name, uniqueness: { case_sensitive: true }
##################################################

  #PAGINACION = 10
  self.per_page = 10

##################################################
	
end

app/models/lent_serial.rb
class LentSerial < ApplicationRecord
	
  belongs_to :lent_model
  belongs_to :lent_color
  belongs_to :lent_kind

  has_many :info_sales
  validates :name, uniqueness: { case_sensitive: true }
 

  def str_name_sale
    "#{name} (P.min: #{price_cost} / P.Max: #{price_shop}" 
  end

##################################################

  #PAGINACION = 10
  self.per_page = 10

##################################################
	
end

app/models/lent_type.rb
class LentType < ApplicationRecord
	validates :name, uniqueness: { case_sensitive: true }
##################################################

  #PAGINACION = 10
  self.per_page = 10

##################################################

end

app/models/monture_type.rb
class MontureType < ApplicationRecord
	validates :name, uniqueness: { case_sensitive: true }
##################################################

  #PAGINACION = 10
  self.per_page = 10

##################################################

end

app/models/sale.rb
class Sale < ApplicationRecord
  
  belongs_to :client
  

  has_many :info_sales
  accepts_nested_attributes_for :info_sales, :allow_destroy => true,  :reject_if => proc { |att| att['price_sale'].blank? }
  
  has_many :accesory_sales
  accepts_nested_attributes_for :accesory_sales, :allow_destroy => true,  :reject_if => proc { |att| att['price_sale'].blank? }

  validates :num_sale, uniqueness: { case_sensitive: true }
  
############################################
 
  def str_created_at
    return created_at.strftime("%d/%m/%Y %I:%M %p")
  end
##################################################

  #PAGINACION = 10
  self.per_page = 10

##################################################

end

app/models/supplier.rb
class Supplier < ApplicationRecord
	belongs_to :type_doc
	validates :num_doc, uniqueness: true
##################################################

  #PAGINACION = 10
  self.per_page = 10

##################################################

end

app/models/type_client.rb
class TypeClient < ApplicationRecord
	has_many :type_docs
	validates :name, uniqueness: { case_sensitive: true }
##################################################

  #PAGINACION = 10
  self.per_page = 10

##################################################

end

app/models/type_doc.rb
class TypeDoc < ApplicationRecord
	belongs_to :type_client

	has_many :clients
	has_many :suppliers

	validates :name, uniqueness: { case_sensitive: true }
##################################################

  #PAGINACION = 10
  self.per_page = 10

##################################################

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
##################################################

  #PAGINACION = 10
  self.per_page = 10

##################################################
         
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user! 
  def index
  	
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/dashboards/index.html.erb
<h1 align="center">Ajustes del sistema</h1>
<br>

<div class="row" align="center">
  <div class="col-xs-6"><%= link_to 'Tipos de Cliente', type_clients_path, class: "btn btn-primary btn-xl col-xs-6 col-sm-4" %></div>
  <div class="col-xs-6"><%= link_to 'Clientes', clients_path, class: "btn btn-primary btn-xl col-xs-6 col-sm-4" %></div>
</div>

<br>
<div class="row" align="center">
  <div class="col-xs-6"><%= link_to 'Tipos de Documento', type_docs_path, class: "btn btn-primary btn-xl col-xs-6 col-sm-4" %></div>
  <div class="col-xs-6"><%= link_to 'Usuarios', users_path, class: "btn btn-primary btn-xl col-xs-6 col-sm-4" %></div>
</div>

<br>
<div class="row" align="center">
  <div class="col-xs-6"><%= link_to 'Proveedores', suppliers_path, class: "btn btn-primary btn-xl col-xs-6 col-sm-4" %></div>
  <div class="col-xs-6"><%= link_to 'Colores de Lente', lent_colors_path, class: "btn btn-primary btn-xl col-xs-6 col-sm-4" %></div>
</div>


<br>
<div class="row" align="center">
  <div class="col-xs-6"><%= link_to 'Marcas de Lente', lent_marks_path, class: "btn btn-primary btn-xl col-xs-6 col-sm-4" %></div>
  <div class="col-xs-6"><%= link_to 'Modelos de Lente', lent_models_path, class: "btn btn-primary btn-xl col-xs-6 col-sm-4" %></div>
</div>

<br>
<div class="row" align="center">
  <div class="col-xs-6"><%= link_to 'Series de Lente', lent_serials_path, class: "btn btn-primary btn-xl col-xs-6 col-sm-4" %></div>
  <div class="col-xs-6"><%= link_to 'Tipo de Monturas',monture_types_path, class: "btn btn-primary btn-xl col-xs-6 col-sm-4" %></div>
</div>

<br>
<div class="row" align="center">
  <div class="col-xs-6"><%= link_to 'Tipos de Lente (receta)', lent_types_path, class: "btn btn-primary btn-xl col-xs-6 col-sm-4" %></div>
  <div class="col-xs-6"><%= link_to 'Ventas',sales_path, class: "btn btn-primary btn-xl col-xs-6 col-sm-4" %></div>
</div>


<br>
<div class="row" align="center">
  <div class="col-xs-6"><%= link_to 'Tipos de Lente', lent_kinds_path, class: "btn btn-primary btn-xl col-xs-6 col-sm-4" %></div>
  <div class="col-xs-6"><%= link_to 'Accesorios de Lente',lent_accesories_path, class: "btn btn-primary btn-xl col-xs-6 col-sm-4" %></div>
</div>

<br>
<div class="row" align="center">
  <div class="col-xs-6"><%= link_to 'Historial de Consultas', history_clients_path, class: "btn btn-primary btn-xl col-xs-6 col-sm-4" %></div>
  <div class="col-xs-6"><%= link_to 'Ventas de Acecsorios',accesory_sales_path, class: "btn btn-primary btn-xl col-xs-6 col-sm-4" %></div>
</div>