config/routes.rb
Rails.application.routes.draw do
  
  resources :accesory_sales
  namespace :api do
    resources :clients
  end
  resources :lent_accesories do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :lent_kinds do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :info_sales do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :sales do 
    match 'search', :via => [:post,:get], :on => :collection
    match 'search_client',:via =>[:get], :on => :collection   
  end  

  resources :lent_types do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :history_clients do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :monture_types do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :lent_models do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :lent_marks do
    match 'search', :via => [:post,:get], :on => :collection
  end

  resources :lent_colors do
    match 'search', :via => [:post,:get], :on => :collection
  end
  
  resources :lent_serials do
    match 'search', :via => [:post,:get], :on => :collection
    match 'find_type_model',:via =>[:get], :on => :collection      
  end

  resources :suppliers do
    match 'search', :via => [:post,:get], :on => :collection
    match 'find_type_doc',:via =>[:get], :on => :collection  
  end

  resources :clients do
    match 'search', :via => [:post,:get], :on => :collection
    match 'find_type_doc',:via =>[:get], :on => :collection      
    resources :history_clients    
  end
 

  resources :type_clients do
     match 'search', :via => [:post,:get], :on => :collection
  end

  resources :type_docs do
     match 'search', :via => [:post,:get], :on => :collection
  end

  resources :accounts do
     match 'search', :via => [:post,:get], :on => :collection
  end
  
  resources :dashboards

  devise_for :users,controllers: {sessions: 'sessions'}
  
  resources :users

   root 'home#index'  
end

app/models/sale.rb
class Sale < ApplicationRecord
  
  belongs_to :client
  

  has_many :info_sales
  accepts_nested_attributes_for :info_sales, :allow_destroy => true,  :reject_if => proc { |att| att['price_sale'].blank? }
  
  has_many :accesory_sales
  accepts_nested_attributes_for :accesory_sales, :allow_destroy => true,  :reject_if => proc { |att| att['price_sale'].blank? }

  validates :num_sale, uniqueness: { case_sensitive: true }
  
############################################
 
  def str_created_at
    return created_at.strftime("%d/%m/%Y %I:%M %p")
  end
##################################################

  #PAGINACION = 10
  self.per_page = 10

##################################################

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
################################################

  def search
    index
    render :index
  end
  # GET /sales
  # GET /sales.json
  def index
    @search_doc = params[:search_doc]

    # INICIO RANSACK
    @query = Sale.ransack(params[:q])    
    @query.num_sale_cont = @search_doc if @search_doc.present?

    # PAGINACION Y ORDEN
    @results =  @query.result(distinct: true).paginate(:page => params[:page] )
     
    # RESULTADO FINAL
    @sales = @results 
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    @lent_serials = LentSerial.all
    @lent_accesories = LentAccesory.all

    5.times do 
      @nested_info_sale = @sale.info_sales.build
    end

    @nested_accesory = @sale.accesory_sales.build

   
  end

  # GET /sales/1/edit
  def edit
     @lent_serials = LentSerial.all
     @lent_accesories = LentAccesory.all
     @client = Client.find(@sale.client_id)
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)
    @lent_serials = LentSerial.all
    @lent_accesories = LentAccesory.all

    respond_to do |format|
      if @sale.save
        format.html { 
          redirect_to @sale
          flash[:success] = 'Se ha creado.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    @lent_serials = LentSerial.all
    @lent_accesories = LentAccesory.all
    @client = Client.find(@sale.client_id)

    respond_to do |format|
      if @sale.update(sale_params)
        format.html { 
          redirect_to @sale
          flash[:success] = 'Se ha actualizado.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { 
        redirect_to sales_url
        flash[:danger] = 'Se ha eliminado.' }
      format.json { head :no_content }
    end
  end

####################################################
  
  def search_client

    @client = Client.where('num_doc = ?', params[:search_doc] ).first

  end 
####################################################

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit!#(:client_id,info_sales_attributes: [:id,:quantity,:client_id,:price_sale,:lent_serial_id,:_destroy])
      #contacts_attributes: [:id, :type_contact, :name, :lastname, :client_id, :position_id, :phone_mail, :phone ,:extension,:phone2,:_destroy ])
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_accesory_sale_fields.erb
<tr class="nested-fields">
  <td><%= f.number_field :quantity,:value=>1, style: 'width:5em', class: 'form-control validate[optional]',:readonly=>true %></td>
  <td><%= f.collection_select :lent_accesory_id, @lent_accesories, :id, :str_name_sale,{}, style: 'width:20em',class: 'selection' %></td>
  <td><%= f.text_field :price_sale, style: 'width:10em', class: 'form-control validate[custom[number]]' %></td>
  <td><%= link_to_remove_association "<img src='/assets/icons/delete.png' width='14' height='14'>".html_safe, f %></td>
</tr>
      

app/views/sales/_form.html.erb
<% javascript "jquery/jquery-1.8.2.min.js" %>
<% javascript "jquery/jquery.validationEngine","jquery/jquery.validationEngine-es" %>
<% jquery_validationengine "doc_search_remote" %>
<% jquery_validationengine "validate_form" %>
<% stylesheet "validationEngine.jquery" %>


<br>
<%= form_for :find_client, url: search_client_sales_path, remote: true, html: { :id=>"doc_search_remote",method: 'get',class: "form-signin" } do |f| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Datos del Cliente</h4>
  </div>
  <div class="panel-body">
    <p id="client_result"></p>
    <br>
    <div class="row">
      <div class="col-xs-3"><strong>N°Documento:</strong></div>
      <div class="col-xs-6"><%= text_field_tag "search_doc",params[:search_doc],:placeholder=>"Completar",class: "form-control validate[required]" %><button type="submit" class="btn btn-danger btn-sm">Buscar</button></div>      
    </div>    
  </div>
</div>
<% end %>

<%= form_for(sale,:html => {id: "validate_form"}) do |f| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2 class="container alert alert-danger"><%= pluralize(sale.errors.count, "error") %> encontrado:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li class="container alert alert-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<br><br>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Datos de la Boleta</h4>
  </div>
  <div class="panel-body">
    <% if @sale.new_record? %>
    <br>
    <div id="client_info" class="row">
      <div class="col-xs-3"><strong>Cliente:</strong></div>
      <div class="col-xs-6"><%= text_field_tag "var",@var,:placeholder=>"Completar",class: "form-control validate[required]",:readonly=>true %></div>
    </div>

    <br>
    <div id="client_info" class="row">
      <div class="col-xs-3"><strong>N°Boleta:</strong></div>
      <div class="col-xs-6"><%= f.text_field :num_sale,:placeholder=>"Completar",class: "form-control validate[required]" %></div>
    </div>    
    <% else %>
    <br>
    <div id="client_info" class="row">
      <div class="col-xs-3"><strong>Cliente:</strong></div>
      <div class="col-xs-6"><%= text_field_tag "var",@client.str_complete_name,:placeholder=>"Completar",class: "form-control validate[required]",:readonly=>true %></div>
    </div>
    <br>
    <div id="client_info" class="row">
      <div class="col-xs-3"><strong>N°Boleta:</strong></div>
      <div class="col-xs-6"><%= f.text_field :num_sale,:placeholder=>"Completar",class: "form-control validate[required]" %></div>
    </div>      
    <% end %> 
  </div>
</div>

<br><br>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Datos de la Venta</h4>
  </div>
  <div class="panel-body">

    <script>
      $.noConflict();
      $(document).ready(function(){
        function init_select1(selector){
          $(selector).select2({
            placeholder: "Seleccione",
            allowClear: true
          });
        };
        function init_select2(selector2){
          $(selector2).select2({
            placeholder: "Seleccione",
            allowClear: true
          });
        };        
        init_select1(".selection")
        init_select2(".selection2")

        $("form").on("cocoon:after-insert", function(_, row){
          field1 = $(row1).find(".selection")
          init_select1(field1);
        });    
        $("form2").on("cocoon:after-insert", function(_, row2){
          field2 = $(row2).find(".selection2")
          init_select2(field2);
        });           
      });
     
    </script>    

    <%= link_to_add_association "Agregar Otro Lente", f, :info_sales, data: {"association-insertion-node" => ".info_sales", "association-insertion-method" => "append"},:class=>"btn btn-success" %>
    <br><br>
    <div class="table-responsive">
      <table class="table">
        <thead class="thead-inverse">
          <tr>
            <th>Cantidad</th>
            <th>Serie/costos</th>
            <th>Precio Final</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody class="info_sales">
        <%= f.fields_for :info_sales do |info_sale| %>
          <%= render 'info_sale_fields', f: info_sale %>
        <% end %>
        </tbody>
      </table>
    </div>

<br><br>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Datos de Accesorios</h4>
  </div>
  <div class="panel-body">

    

    <%= link_to_add_association "Agregar Otro Lente", f, :accesory_sales, data: {"association-insertion-node" => ".accesory_sales", "association-insertion-method" => "append"},:class=>"btn btn-success" %>
    <br><br>
    <div class="table-responsive">
      <table class="table">
        <thead class="thead-inverse">
          <tr>
            <th>Cantidad</th>
            <th>Serie/costos</th>
            <th>Precio Final</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody class="accesory_sales">
        <%= f.fields_for :accesory_sales do |accesory_sale| %>
          <%= render 'accesory_sale_fields', f: accesory_sale %>
        <% end %>
        </tbody>
      </table>
    </div>
     
    <br>
    <div class="actions" align="center">
      <%= f.submit "Guardar", class: "btn btn-success" %>
      <%= link_to 'Regresar', sales_path , class: "btn btn-warning"%>
    </div>
    <% end %>
  </div>
</div>

app/views/sales/_info_sale_fields.erb
<tr class="nested-fields">
  <td><%= f.number_field :quantity,:value=>1, style: 'width:5em', class: 'form-control validate[optional]',:readonly=>true %></td>
  <td><%= f.collection_select :lent_serial_id, @lent_serials, :id, :str_name_sale,{}, style: 'width:20em',class: 'selection' %></td>
  <td><%= f.text_field :price_sale, style: 'width:10em', class: 'form-control validate[custom[number]]' %></td>
  <td><%= link_to_remove_association "<img src='/assets/icons/delete.png' width='14' height='14'>".html_safe, f %></td>
</tr>
      

app/views/sales/edit.html.erb
<h1 align="center">Editar Venta</h1>
<br>

<%= render 'form', sale: @sale %>
 

app/views/sales/index.html.erb
<h1 align="center">Ventas</h1>
<br>

<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Búsqueda</h4>
  </div>
  <div class="panel-body">
    <%= form_for @query, url: [:search,:sales], html: { method: 'post'}  do %> 
      <p><label>N°Boleta:</label>
      <%= text_field_tag "search_doc", params[:search_doc], class: "form-control" %></p>
      <p><%= submit_tag "Buscar",:class=>"btn bg-color-blueDark txt-color-white" %></p> 
    <% end %>
  </div>
</div>

<br>
<%= link_to 'Nuevo Venta', new_sale_path, class: "btn btn-primary" %>
<br><br>

<div class="table-responsive">
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>N°Boleta</th>
        <th>Cliente</th>
        <th>F.Compra</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.num_sale %></td>
        <td><%= sale.client.str_complete_name %></td>
        <td><%= sale.str_created_at %></td>
        <td>
        <%= link_to "<span class='glyphicon glyphicon-zoom-in' aria-hidden='true'></span>".html_safe, sale, class: "btn btn-info"  %>
        <%= link_to "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span>".html_safe, edit_sale_path(sale) ,class: "btn btn-success"  %>
        <%= link_to "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span>".html_safe, sale, class: "btn btn-danger", method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div  class="col-sm-6 text-main"><br/><br/>
  <%= page_entries_info  @sales  , :page_links => false %>
</div>

<div  class="col-sm-6 text-right">
  <%= will_paginate @sales, :params => params, :class => 'pagination2', :previous_label=>">", :next_label => ">",inner_window: 1, outer_window: 1 %>
</div>

 

app/views/sales/new.html.erb
<h1 align="center">Nueva Venta</h1>
<br>

<%= render 'form', sale: @sale %>
 

app/views/sales/search_client.js.erb
$("#client_result").html('<%= j render partial: "sales/partials/client_result" %>')

<% if @client.present? %>
$("#client_info").html('<div class="col-xs-3"><strong>Cliente:</strong></div><div class="col-xs-6"><%= text_field_tag "var_client", @client.name.upcase ,class: "form-control validate[required]",:readonly =>true %><%= hidden_field_tag "client", @client.id, :name=>"sale[client_id]" %></div>')
<% else %>
$("#client_info").html('<div class="col-xs-3"><strong>Cliente:</strong></div><div class="col-xs-6"><%= text_field_tag "var_client", "",class: "form-control validate[required]",:readonly => true  %></div>')
<% end %>

app/views/sales/show.html.erb
<br>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Datos del Cliente</h4>
  </div>
  <div class="panel-body">
    <br>
    <div class="row">
      <div class="col-xs-3"><strong>N°Documento:</strong></div>
      <div class="col-xs-6"><%= @sale.client.num_doc %></div>      
    </div>  

    <br>
    <div class="row">
      <div class="col-xs-3"><strong>Cliente:</strong></div>
      <div class="col-xs-6"><%= @sale.client.str_complete_name %></div>      
    </div>      
  </div>
</div>
 
<br><br>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Datos de la Boleta</h4>
  </div>
  <div class="panel-body">
    <br>
    <div id="client_info" class="row">
      <div class="col-xs-3"><strong>N°Boleta:</strong></div>
      <div class="col-xs-6"><%=@sale.num_sale %></div>
    </div>    
  </div>
</div>

<br><br>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Datos de la Venta</h4>
  </div>
  <div class="panel-body">
  	<div class="table-responsive">
  	  <table class="table" id="info_sales">
  	    <thead class="thead-inverse">
  	      <tr>
  	        <th>Cantidad</th>
  	        <th>Serie del Lente</th>
  	        <th>Precio de Venta</th>
  	      </tr>
  	    </thead>
  	    <tbody>
  	    <% @sale.info_sales.each do |info_sale_form| %>
  	      <tr class="fields">
  	        <td><%= info_sale_form.quantity %></td>
  	        <td><%= info_sale_form.lent_serial.name %></td>
  	        <td><%= info_sale_form.price_sale %></td>
  	     </tr>
  	     <% end %>      
  	    </tbody>
  	  </table>
  	</div>
  </div>
</div>

<% if @sale.accesory_sales.count > 0%>
<br><br>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Datos de Accesorios vendidos</h4>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table" id="info_sales">
        <thead class="thead-inverse">
          <tr>
            <th>Cantidad</th>
            <th>Accesorio</th>
            <th>Precio de Venta</th>
          </tr>
        </thead>
        <tbody>
        <% @sale.accesory_sales.each do |accesory_sale_form| %>
          <tr class="fields">
            <td><%= accesory_sale_form.quantity %></td>
            <td><%= accesory_sale_form.lent_accesory.name %></td>
            <td><%= accesory_sale_form.price_sale %></td>
         </tr>
         <% end %>      
        </tbody>
      </table>
    </div>
  </div>
</div>
<% end %>